
require 'net/http'
require 'uri'
require 'json'
require 'csv'

ALL_ISSUES=[]
start_at = 0
while true do
  puts start_at
  uri = URI.parse("https://<jira-domain-name>.atlassian.net/rest/api/2/search?jql=""created >= 2021-08-31 AND created <= 2022-09-01 AND issuetype = Bug order by created DESC""&maxResults=100&startAt="+start_at.to_s)
  request = Net::HTTP::Get.new(uri)
  request.content_type = "application/json"
  request["Authorization"] = "Basic <auth_token generated by echo -n $CARBON_EMAIL:$JIRA_API_TOKEN | base64>"
  req_options = {
    use_ssl: uri.scheme == "https",
  }
  response = Net::HTTP.start(uri.hostname, uri.port, req_options) do |http|
    http.request(request)
  end
  puts response.code
  response_json = JSON.parse(response.body)
  start_at = start_at+100
  ALL_ISSUES = ALL_ISSUES + response_json["issues"]
  print(response_json["issues"].first["key"], " - ", response_json["issues"].first["fields"]["created"], "\n")
  break if(response_json["total"].to_i <= start_at)
end


def write_to_csv(issues)
  CSV.open("issues.csv", "wb") do |csv|
    csv << [ "KEY", "SUMMARY", "ASSIGNEE", "REPORTER", "STATUS", "CREATED_AT", "UPDATED_AT", "DESCRIPTION"]
    issues.each do |issue|
      csv << [
        issue["key"],
        issue["fields"]["summary"],
        issue["fields"]["assignee"].nil? ? "" : issue["fields"]["assignee"]["emailAddress"],
        issue["fields"]["creator"]["emailAddress"],
        issue["fields"]["status"]["name"],
        issue["fields"]["created"],
        issue["fields"]["updated"],
        issue["fields"]["description"]
      ]
    end
  end
end

write_to_csv(ALL_ISSUES)